### ISSUE TITLE
The use of babel-preset-es2015

### ISSUE THREAD

**Issue by maotora** [joykare/js-workshop#2]
I'm not sure about your further uses with this repo but it's better if you consider to start using `babel-preset-latest` which includes `es2015` & `es2016` and possibly `es2017` as said [here](https://www.npmjs.com/package/babel-preset-latest). 

*Remembering 2015 is 2 years ago, and we way past that generators era :-) *.

**Comment by joykare** [comment]
Hey @maotora thanks thanks. Cant wait to get more issues opened and solved by you.

**Comment by maotora** [comment]
Aww..  😊 😊 stop it now.
